KEYWORDS = [
    # ========== 1. WYSOKA WYDAJNOŚĆ (presja wyników) ==========
    "kultura wysokiej wydajności",
    "wysoka kultura pracy",
    "wysokiej wydajności",
    "środowisko wysokich wyników",
    "wysokich wyników",
    "high performance",
    "high-performance",
    "nastawienie na wyniki",
    "orientacja na wyniki",
    "wyniki ponad wszystko",
    "wyniki się liczą",
    "liczą się tylko wyniki",
    "kultura ciągłego doskonalenia",
    "kultura efektywności",
    "środowisko nastawione na sukces",
    "wymagające środowisko pracy",
    "ambitne środowisko",
    "kultura doskonałości",
    "performance driven",
    "performance-driven",
    "osiąganie wyników",
    "ukierunkowanie na wyniki",
    "meritokracja",
    "rezultaty mają znaczenie",
    "wyniki są najważniejsze",
    "skupienie na rezultatach",
    "result-oriented",
    "result driven",
    "drive for results",
    "delivery focused",
    "delivery-driven",
    "output oriented",
    "output-based",
    "wyniki przede wszystkim",
    "performance oriented",
    "ciągłe podnoszenie poprzeczki",
    "podnoszenie poprzeczki",
    "wymagamy wyników",
    "oczekujemy wyników",
    "kultura odpowiedzialności za wynik",
    "wynik to podstawa",
    "efektywność przede wszystkim",
    "highest standards",
    "zero tolerance for mediocrity",
    "nie akceptujemy przeciętności",
    "dążymy do perfekcji",
    "perfekcjonizm",
    "perfekcyjność",
    "excellence driven",
    "pursuit of excellence",

    # ========== 2. RODZINNA ATMOSFERA (granice zawodowe) ==========
    "jesteśmy jak rodzina",
    "jak rodzina",
    "rodzinna atmosfera",
    "pracujemy jak rodzina",
    "rodzinne środowisko",
    "traktujemy się jak rodzinę",
    "family atmosphere",
    "family feeling",
    "family-like",
    "family oriented",
    "jesteśmy zgraną paczką",
    "zgraną paczką",
    "atmosfera jak w domu",
    "jesteśmy jedną rodziną",
    "rodzinny klimat",
    "poczucie przynależności jak w rodzinie",
    "nasz team to rodzina",
    "jesteśmy rodziną",
    "pracownicy to rodzina",
    "czuj się jak w domu",
    "praca w rodzinnej firmie (ale nie w sensie własności)",
    "kameralny zespół",
    "domowa atmosfera",
    "nieformalne relacje",
    "brak dystansu",
    "wszyscy się znają",
    "jesteśmy blisko",
    "team jak rodzina",
    "wspieramy się jak rodzina",
    "rodzinne wartości",
    "family business vibe",
    "jesteśmy dla siebie jak rodzina",
    "atmosfera bez spiny",
    "swobodna atmosfera",
    "luz w pracy",

    # ========== 3. STRES I PRESJA (wprost lub między wierszami) ==========
    "odporność na stres",
    "praca pod presją",
    "pod presją",
    "praca pod presją czasu",
    "pod presją czasu",
    "presja czasu",
    "umiejętność pracy w warunkach niepewności",
    "w warunkach niepewności",
    "odporność psychiczna",
    "radzenie sobie ze stresem",
    "zachowanie spokoju pod presją",
    "zimna krew w sytuacjach stresowych",
    "zimna krew",
    "umiejętność pracy w stresie",
    "tolerancja na stres",
    "praca pod dużą presją",
    "silna psychika",
    "praca w wymagających warunkach",
    "high pressure",
    "high-pressure",
    "stressful environment",
    "umiejętność działania pod presją",
    "odporność na trudne sytuacje",
    "praca w trudnych warunkach",
    "wysoka odporność na stres",
    "wysoka kultura pracy pod presją",
    "presja nie jest ci straszna",
    "nie boisz się presji",
    "presja działa na ciebie mobilizująco",
    "praca na pełnych obrotach",
    "non-stop w gotowości",
    "nerwy ze stali",
    "stalowe nerwy",
    "odporność na frustrację",
    "radzenie sobie z przeciwnościami",
    "praca w ogniu",
    "praca na pierwszej linii",
    "high-stakes environment",
    "umiejętność pracy w kryzysie",
    "praca w sytuacjach kryzysowych",
    "ciśnienie",
    "wytrzymałość psychiczna",
    "mental toughness",
    "resilience",
    "highly demanding environment",

    # ========== 4. WYNAGRODZENIE PROWIZYJNE / NIEJAWNE (ryzyko niskiej podstawy) ==========
    "wynagrodzenie uzależnione od efektów",
    "atrakcyjny system prowizyjny",
    "system prowizyjny",
    "prowizja bez górnego limitu",
    "bez górnego limitu",
    "zarobki adekwatne do zaangażowania",
    "wynagrodzenie do uzgodnienia",
    "do uzgodnienia",
    "wynagrodzenie zależne od wyników",
    "nieograniczone zarobki",
    "zarabiasz tyle ile chcesz",
    "twoje zarobki zależą od ciebie",
    "pensja do negocjacji",
    "do negocjacji",
    "wynagrodzenie do omówienia",
    "do omówienia",
    "atrakcyjne wynagrodzenie",
    "konkurencyjne wynagrodzenie",
    "wynagrodzenie dopasowane do kandydata",
    "płaca do uzgodnienia",
    "zarobki do rozmowy",
    "możliwości zarobkowe",
    "wysokie prowizje",
    "nieograniczony potencjał zarobkowy",
    "system premiowy za wyniki",
    "wynagrodzenie adekwatne",
    "rynkowe wynagrodzenie",
    "wynagrodzenie premiowe",
    "premia uznaniowa",
    "system bonusowy",
    "bonus uzależniony od wyników",
    "wynagrodzenie zadaniowe",
    "stawka + prowizja",
    "niska podstawa + wysoka prowizja",
    "twój sukces to twoja pensja",
    "zarabiaj tyle, na ile cię stać",
    "potencjalnie wysokie zarobki",
    "widełki: 1000 - 20000",
    "wynagrodzenie od do",
    "dochód nieograniczony",
    "zarobki bez górnej granicy",
    "skaluj swoje zarobki",
    "wynagrodzenie motywacyjne",
    "wynagrodzenie efektywnościowe",

    # ========== 5. WIELOZADANIOWOŚĆ (jako przykrywka chaosu) ==========
    "wielozadaniowość",
    "multitasking",
    "multi-tasking",
    "umiejętność pracy na wielu frontach",
    "praca na wielu projektach jednocześnie",
    "obsługa wielu klientów jednocześnie",
    "jednoczesna praca nad wieloma projektami",
    "zdolność do równoległej pracy",
    "praca na kilku frontach",
    "praca równoległa",
    "przełączanie się między zadaniami",
    "task switching",
    "jednoczesna realizacja zadań",
    "kilka rzeczy naraz",
    "radzenie sobie z wieloma zadaniami",
    "umiejętność żonglowania zadaniami",
    "żonglowanie projektami",
    "praca na wielu wątkach",
    "jednoczesne prowadzenie kilku procesów",
    "równoczesna obsługa",
    "wielowątkowość",
    "równoległe realizowanie",

    # ========== 6. NIEFORMALNE TYTUŁY (maskujące niską rangę i wyzysk) ==========
    "rockstar",
    "ninja",
    "guru",
    "ewangelista",
    "wizard",
    "czarodziej",
    "superhero",
    "champion",
    "haker",
    "hacker",
    "jedi",
    "unicorn",
    "top performer",
    "superstar",
    "mastermind",
    "coding ninja",
    "code ninja",
    "marketing guru",
    "sales rockstar",
    "design wizard",
    "excel ninja",
    "product evangelist",
    "customer champion",
    "support superhero",
    "ops jedi",
    "growth hacker",
    "ninja developer",
    "rockstar developer",
    "guru of everything",
    "magician",
    "wunderkind",
    "czarodziej excela",
    "mistrz klawiatury",
    "ninja sprzedaży",
    "rockstar handlowca",

    # ========== 7. CHAOS / DYNAMIKA (jako stały stan) ==========
    "chaotyczne środowisko",
    "dynamicznie zmieniające się otoczenie",
    "dynamicznie zmieniające",
    "praca w warunkach niepewności",
    "zarządzanie chaosem",
    "umiejętność pracy w chaosie",
    "dynamiczne środowisko",
    "szybko zmieniające się środowisko",
    "klimat startupowy",
    "startupowy",
    "startup atmosphere",
    "startup mindset",
    "startup culture",
    "szybkie zmiany",
    "ciągłe zmiany",
    "dynamicznie rozwijająca się firma",
    "środowisko w ciągłym ruchu",
    "szybko ewoluujące środowisko",
    "bardzo dynamiczne",
    "nieustanne zmiany",
    "praca w zmiennym środowisku",
    "tempo jak w startupie",
    "chaos produktywny",
    "kontrolowany chaos",
    "organiczny chaos",
    "nic nie jest stałe",
    "jutro może być inaczej",
    "zmiana to jedyna stała",
    "highly dynamic",
    "constantly evolving",
    "everything changes",
    "brak rutyny",
    "nigdy nie wiesz co przyniesie dzień",
    "work in ambiguity",
    "tolerancja na niejednoznaczność",
    "rada sobie w niejasnych sytuacjach",
    "nie ma sztywnych reguł",
    "wszystko płynie",
    "płynne środowisko",

    # ========== 8. ELATYCZNY CZAS PRACY (niewolniczy) ==========
    "elastyczny czas pracy",
    "elastyczne godziny pracy",
    "elastyczne godziny zatrudnienia",
    "elastyczne godziny",
    "elastyczny grafik",
    "flextime",
    "nienormowany czas pracy",
    "nienormowany",
    "elastyczność w godzinach",
    "praca w elastycznych godzinach",
    "elastyczny wymiar czasu pracy",
    "możliwość dostosowania godzin",
    "praca bez sztywnych godzin",
    "bez sztywnych godzin",
    "godziny dopasowane do projektu",
    "elastyczne podejście do czasu pracy",
    "brak stałych godzin pracy",
    "brak stałych godzin",
    "elastyczność czasowa",
    "praca w różnych godzinach",
    "godziny uzależnione od projektu",
    "praca od poniedziałku do niedzieli",
    "dyspozycyjność czasowa",
    "dostępność poza biurem",
    "godziny pracy do uzgodnienia",
    "system zadaniowy (z nielimitowanym czasem)",
    "jesteśmy elastyczni",
    "dostosuj godziny do potrzeb firmy",
    "nierównomierne obciążenie godzinowe",
    "praca również w weekendy w zależności od potrzeb",
    "dostępność w godzinach wieczornych",

    # ========== 9. POZORNE BENEFITY (red flag - brak prawdziwych benefitów) ==========
    "owocowe czwartki",
    "owocowe",
    "owoce w biurze",
    "owoce",
    "świeże owoce",
    "kawa i herbata",
    "strefa relaksu",
    "piłkarzyki",
    "stół do ping-ponga",
    "ping-pong",
    "ping pong",
    "imprezy integracyjne",
    "wyjazdy integracyjne",
    "integracyjne",
    "paczki świąteczne",
    "kawa na koszt firmy",
    "bezpłatna kawa",
    "praca w nowoczesnym biurze",
    "dostęp do kuchni",
    "chillout room",
    "chillout",
    "strefy odpoczynku",
    "konsola do gier",
    "gry planszowe",
    "słodycze w biurze",
    "piwo w piątek",
    "piwo w biurze",
    "darmowa herbata",
    "darmowe napoje",
    "lody w lecie",
    "pizza w piątek",
    "pizza friday",
    "śniadaniowe czwartki",
    "tłusty czwartek z pączkiem",
    "owocowe wtorki",
    "kuchnia wyposażona",
    "ekspres do kawy",
    "napój gazowane gratis",
    "imprezy co miesiąc",
    "owoce i warzywa",
    "zdrowa przekąska",
    "bilonówka",
    "stół do tenisa stołowego",
    "gaming room",
    "playstation w biurze",
    "xbox w pracy",
    "stoliki do piłkarzyków",

    # ========== 10. MŁODY / AMBITNY ZESPÓŁ (niska lojalność, wysokie oczekiwania) ==========
    "młody zespół",
    "ambitny zespół",
    "praca w młodym gronie",
    "młodym gronie",
    "praca z młodymi ludźmi",
    "młodzi i dynamiczni",
    "energiczny zespół",
    "świeży zespół",
    "praca w młodym środowisku",
    "young team",
    "dynamiczny młody team",
    "entuzjastyczny zespół",
    "młodzi specjaliści",
    "passion-driven team",
    "zespół pełen energii",
    "grono młodych zapaleńców",
    "młodzi ambitni",
    "średnia wieku poniżej 30",
    "średnia wieku 25",
    "dwudziestokilkuletni zespół",
    "młodzieżowy vibe",
    "energia młodości",
    "early career team",
    "junior team",
    "świeżo po studiach",
    "młodzi wilcy",
    "młodzi i głodni sukcesu",
    "hungry team",

    # ========== 11. DYSPOZYCYJNOŚĆ (gotowość 24/7) ==========
    "dyspozycyjność",
    "dyspozycyjność weekendowa",
    "weekendowa",
    "gotowość do wyjazdów służbowych",
    "wyjazdy służbowe",
    "stały kontakt",
    "dostępność pod telefonem",
    "pod telefonem",
    "bycie pod telefonem",
    "praca w weekendy",
    "praca w nadgodzinach",
    "gotowość do pracy w nadgodzinach",
    "nadgodziny",
    "możliwość pracy w niestandardowych godzinach",
    "brak ograniczeń czasowych",
    "dyspozycja",
    "gotowość na wyjazdy",
    "praca w systemie zmianowym",
    "system zmianowy",
    "praca nocna",
    "praca po godzinach",
    "kontakt poza godzinami",
    "dostępność 24/7",
    "24/7",
    "praca na zmiany",
    "praca w trybie on-call",
    "on-call",
    "dyżury telefoniczne",
    "dyżury w weekend",
    "praca w święta",
    "praca w niedziele",
    "praca w soboty",
    "dyspozycyjność w dni wolne",
    "dostępność w każdym momencie",
    "zawsze pod ręką",
    "gotowość do przyjazdu w każdej chwili",
    "gotowość operacyjna 24h",
    "stand-by",
    "reagowanie po godzinach",
    "praca na telefon",
    "bycie na baterii 24/7",

    # ========== 12. NIEKREŚLONY ZAKRES OBOWIĄZKÓW (wszystko i nic) ==========
    "inne obowiązki zlecone przez przełożonego",
    "inne obowiązki",
    "szeroki zakres obowiązków",
    "osoba do wszystkiego",
    "wszechstronność",
    "inne zadania wynikające",
    "oraz inne zadania",
    "i inne zadania",
    "dodatkowe zadania powierzone",
    "realizacja innych zadań",
    "różnorodne zadania",
    "zadania ad hoc",
    "ad hoc",
    "obsługa bieżących spraw",
    "inne zadania zgodnie z potrzebami",
    "zadania zlecone przez management",
    "różnorodny zakres działań",
    "praca na różnych polach",
    "elastyczny zakres obowiązków",
    "zadania nieujęte w opisie",
    "dodatkowe obowiązki",
    "i inne czynności",
    "wszystko co potrzebne",
    "pomoc przy innych projektach",
    "zadania wynikające z bieżących potrzeb",
    "wsparcie tam gdzie trzeba",
    "prace porządkowe",
    "działania nieprzewidziane",
    "obowiązki zmienne",
    "wypełnianie luk",
    "ogólne wsparcie operacyjne",
    "and other duties as assigned",
    "coś jeszcze może wyskoczyć",
    "praca w trybie wszędziepola",
    "generalista",
    "jack of all trades",
    "master of none",

    # ========== 13. SZYBKIE TEMPO / TIGHT DEADLINES ==========
    "szybkie tempo pracy",
    "szybkie tempo",
    "praca w szybkim tempie",
    "wysokie tempo",
    "praca na wczoraj",
    "szybkie terminy",
    "tight deadlines",
    "fast-paced",
    "szybko działający zespół",
    "praca pod time pressure",
    "time pressure",
    "krótkie terminy realizacji",
    "dynamiczne tempo",
    "intensywne tempo",
    "wymagające terminy",
    "praca w trybie pilnym",
    "tempo startupu",
    "high-paced",
    "agile pace",
    "krótkie deadliny",
    "deadline to świętość",
    "dotrzymywanie deadline'ów za wszelką cenę",
    "terminy się nie przesuwają",
    "pilne zadania na już",
    "reagowanie w trybie natychmiastowym",
    "natychmiastowa realizacja",
    "wysoka presja czasowa",
    "clock is ticking",
    "time-sensitive",
    "godzina jest ważna",
    "praca z minutnikiem",
    "zadania do zamknięcia w trybie ekspresowym",
    "fast delivery",
    "short turnaround",
    "szybki time-to-market",
    "praca w systemie just-in-time",

    # ========== 14. PRACA DLA PASJONATÓW (wypasienie granicy praca-życie) ==========
    "praca dla pasjonatów",
    "szukamy pasjonatów",
    "pasjonaci",
    "pasja do pracy",
    "robimy to z pasją",
    "praca z pasją",
    "z pasją",
    "szukamy kogoś z pasją",
    "miłośnicy swojej pracy",
    "pokochaj swoją pracę",
    "praca to styl życia",
    "pasjonaci branży",
    "szukamy entuzjastów",
    "pasja zamiast rutyny",
    "praca to powołanie",
    "powołanie",
    "misja nie praca",
    "dołącz do ludzi z misją",
    "praca z zamiłowania",
    "pasjonat swojej dziedziny",
    "work is passion",
    "praca z sercem",
    "to więcej niż praca",
    "to nasze życie",
    "żyjemy tym",
    "oddajemy serce",
    "praca jako hobby",
    "hobby które stało się pracą",
    "jeśli to nie twoja pasja, nie pasujesz",
    "szukamy kogoś, kto żyje pracą",
    "praca jako misja życiowa",
    "nie szukamy pracowników, szukamy pasjonatów",
    "praca = spełnienie",
    "to nie tylko etat, to styl życia",

    # ========== 15. POZYTYWNE NASTAWIENIE / ZAKAZ NARZEKANIA ==========
    "szukanie rozwiązań nie problemów",
    "pozytywne nastawienie",
    "nie boimy się ciężkiej pracy",
    "podejście can-do",
    "can-do attitude",
    "can-do",
    "szukamy kogoś z drivem",
    "z drivem",
    "szukamy kogoś z iskrą",
    "z iskrą",
    "wyjście poza strefę komfortu",
    "poza strefę komfortu",
    "strefę komfortu",
    "proaktywna postawa",
    "szukamy optymistów",
    "pozytywna energia",
    "growth mindset",
    "mentalność wzrostu",
    "nastawienie na rozwiązania",
    "szukamy ludzi z inicjatywą",
    "własna inicjatywa",
    "szukamy kogoś z wewnętrznym motorem",
    "szukamy samodzielnych inicjatorów",
    "nie narzekamy, działamy",
    "skupiamy się na rozwiązaniach",
    "narzekanie nie jest wskazane",
    "zero narzekania",
    "brak miejsca na pesymizm",
    "nie oczekujemy marudzenia",
    "szukamy wojowników a nie maruderów",
    "pozytywny mindest",
    "energia i uśmiech",
    "nie ma złych nastrojów",
    "nie ma złych dni",
    "nie ma wymówek",
    "nie ma problemów są wyzwania",

    # ========== 16. EMPOWERMENT BEZ POKRYCIA (odpowiedzialność bez władzy) ==========
    "dajemy ci władzę",
    "empowerment",
    "upoważniamy cię",
    "masz wpływ na swoją pracę",
    "autonomia w działaniu",
    "zarządzasz swoją pracą",
    "ty decydujesz",
    "pełna autonomia",
    "swoboda decyzyjna",
    "empowered team",
    "employee empowerment",
    "twój głos się liczy",
    "masz realny wpływ",
    "wolna ręka w działaniu",
    "decyzyjność",
    "podejmujesz decyzje",
    "jesteś gospodarzem swojej roli",
    "samodzielne decyzje",
    "pełne zaufanie",
    "zaufanie na starcie",
    "nie ma nadzoru",
    "action-oriented empowerment",
    "możesz działać jak własny boss",
    "jesteś jak przedsiębiorca w firmie",
    "intrapreneur",
    "intrapreneruship",
    "samodzielność decyzyjna",

    # ========== 17. ZAANGAŻOWANIE PONAD NORMĘ (wypalenie) ==========
    "zaangażowanie 110%",
    "110%",
    "zaangażowanie po godzinach",
    "gotowość do poświęceń",
    "poświęcenia",
    "wkładamy serce w to co robimy",
    "praca z pełnym zaangażowaniem",
    "poświęcenie dla firmy",
    "extra mile",
    "going the extra mile",
    "ponad przeciętność",
    "100% zaangażowania",
    "pełne poświęcenie",
    "praca wykraczająca poza obowiązki",
    "above and beyond",
    "ponad obowiązki",
    "praca z sercem",
    "zaangażowanie bez kompromisów",
    "praca z pełną parą",
    "nie odmawiamy sobie niczego dla firmy",
    "firma na pierwszym miejscu",
    "praca przed życiem prywatnym",
    "wolimy pracować niż odpoczywać",
    "weekend? a co to?",
    "praca w święta? czemu nie",
    "krew, pot i łzy",
    "dajemy z siebie wszystko",
    "200% zaangażowania",
    "bezgraniczne zaangażowanie",
    "cały siebie dla firmy",
    "oddanie firmie",
    "lojalność bez granic",
    "praca przede wszystkim",
    "job comes first",

    # ========== 18. PŁASKA STRUKTURA / BRAK ŚCIEŻKI KARIERY ==========
    "płaska struktura",
    "brak hierarchii",
    "otwarte drzwi",
    "polityka otwartych drzwi",
    "brak barier",
    "horyzontalna struktura",
    "flat structure",
    "flat organization",
    "bez korporacyjnych zasad",
    "brak sztywnych procedur",
    "bez biurokracji",
    "bez korporacyjnej biurokracji",
    "non-hierarchical",
    "swobodna organizacja",
    "brak sztywnych ram",
    "bez sztywnych zasad",
    "każdy mówi każdemu po imieniu",
    "nie ma działów",
    "nie ma stanowisk",
    "brak tytułów",
    "wszyscy są równi",
    "kultura open door",
    "dostęp do każdego",
    "bez formalności",
    "bez dress code'u",
    "nie ma korpo-sztywności",
    "zero korpo",
    "brak szczebli",
    "jeden poziom",
    "wszyscy na tym samym poziomie",
    "każdy ma głos",
    "każdy może do każdego",
    "horyzontalna kariera",

    # ========== 19. PRACA ZDALNA DOPIERO PO WDROŻENIU (sygnał mikrozarzadzania) ==========
    "możliwość pracy zdalnej po wdrożeniu",
    "praca zdalna po okresie próbnym",
    "hybrydowo po wdrożeniu",
    "zdalnie po adaptacji",
    "remote po onboardingu",
    "po onboardingu",
    "praca zdalna po adaptacji",
    "po wdrożeniu możliwość pracy zdalnej",
    "docelowo praca zdalna",
    "możliwość pracy hybrydowej po wdrożeniu",
    "home office po wdrożeniu",
    "praca zdalna po stażu",
    "zdalnie po próbnym",
    "możliwość pracy z domu po wdrożeniu",
    "po wdrożeniu",
    "home office po okresie próbnym",
    "praca zdalna po 3 miesiącach",
    "zdalnie od zaraz? tylko po wdrożeniu",
    "najpierw onboarding w biurze, potem ewentualnie zdalnie",
    "hybryda po okresie adaptacji",
    "zdalnie możliwe, ale nie od razu",
    "praca zdalna po zdobyciu zaufania",
    "elastyczność po czasie",
    "praca z domu dozwolona po wdrożeniu",

    # ========== 20. SZYBKI AWANS (sygnał rotacji i wypalenia na wyższych stanowiskach) ==========
    "możliwość szybkiego awansu",
    "szybki awans",
    "szybki rozwój kariery",
    "szybka ścieżka awansu",
    "szybkie możliwości rozwoju",
    "szybki wzrost",
    "szybkie przejście na wyższe stanowisko",
    "przyspieszony awans",
    "możliwość awansu już po pierwszym roku",
    "awans za wyniki",
    "ekspresowy rozwój",
    "możliwość szybkiego wzrostu",
    "szybka ścieżka do zarządzania",
    "awans po 6 miesiącach",
    "szybka promocja",
    "od juniora do directora w rok",
    "dynamiczny awans",
    "wymarzona kariera w ekspresowym tempie",
    "szybko w górę",
    "zostań liderem w rok",
    "awans gwarantowany przy wynikach",
    "szybki awans dla ambitnych",
    "przyspieszona ścieżka menedżerska",
    "fast track",
    "fast promotion",
    "fast career growth",

    # ========== 21. NAGINACZ ZASAD (wrogość do procedur i BHP) ==========
    "naginanie zasad",
    "myślenie poza schematami",
    "przełamywanie granic",
    "łamanie zasad",
    "wychodzenie poza utarte schematy",
    "niestandardowe myślenie",
    "rule-bender",
    "disruptor",
    "disruption",
    "breaking the rules",
    "thinking outside the box",
    "outside the box",
    "myślenie out of the box",
    "out of the box",
    "poza schematami",
    "burzenie stereotypów",
    "kwestionowanie status quo",
    "rewolucyjne myślenie",
    "brak ograniczeń w myśleniu",
    "niekonwencjonalne podejście",
    "nie boimy się łamać zasad",
    "tu nie ma zasad",
    "reguły są po to, by je łamać",
    "nie ma rzeczy niemożliwych",
    "testujemy granice",
    "przesuwamy granice",
    "nie słuchamy procedur",
    "procedury nas nie ograniczają",
    "działamy niezgodnie ze schematem",
    "schematy są dla nudziarzy",
    "non-conformist",
    "rebel",
    "buntownik",

    # ========== 22. SAMODZIELNA NAUKA BEZ WSPARCIA FIRMY ==========
    "gotowość do nauki nowych rzeczy",
    "chęć do nauki",
    "self-learning",
    "samodzielne zdobywanie wiedzy",
    "ciągłe doskonalenie się",
    "umiejętność szybkiego uczenia się",
    "szybkie przyswajanie wiedzy",
    "silna motywacja do nauki",
    "stałe podnoszenie kwalifikacji",
    "nauka na bieżąco",
    "gotowość do ciągłego uczenia się",
    "otwartość na nowe technologie",
    "samodoskonalenie",
    "ciągły rozwój osobisty",
    "umiejętność uczenia się w biegu",
    "samodzielne szukanie rozwiązań",
    "własny development bez wsparcia",
    "żadnych szkoleń, tylko własna inicjatywa",
    "nie czekaj na gotowca, sam się naucz",
    "google to twój przyjaciel",
    "stackoverflow zamiast mentora",
    "docieramy w boju",
    "uczymy się na własnych błędach",
    "nie ma onboardingu, rzucamy na głęboką wodę",
    "samodzielne ogarnianie",
    "uczenie się na zadaniach",
    "praktyka zamiast teorii",
    "brak budżetu szkoleniowego",
    "nie ma mentora, jest wikipeda",
    "jeśli nie wiesz, sam się dowiedz",

    # ========== 23. CULTURE FIT / WYSOKA KULTURA OSOBISTA (presja konformizmu) ==========
    "wysoka kultura osobista",
    "dopasowanie do zespołu",
    "culture fit",
    "cultural fit",
    "pasowanie do kultury",
    "wartości zgodne z naszymi",
    "dzielenie wspólnych wartości",
    "zgodność z kulturą organizacyjną",
    "dopasowanie do wartości firmy",
    "poszukujemy kogoś kto pasuje",
    "odpowiednie nastawienie",
    "zgodność z naszą kulturą",
    "dopasowanie kulturowe",
    "musisz pasować",
    "nie każdy tu pasuje",
    "szukamy kogoś na swój vibe",
    "dopasowanie personalne",
    "musisz być jednym z nas",
    "my tu tworzymy wyjątkową kulturę",
    "nie dla każdego",
    "tylko dla wybranych",
    "jeśli nie pasujesz, nie aplikuj",
    "dopasowanie do naszych wartości",
    "wartości: tu wpisz cokolwiek",
    "kultura > kompetencje",
    "nastawienie > umiejętności",

    # ========== 24. LOJALNOŚĆ (wersja jednostronna - wykorzystanie) ==========
    "lojalność",
    "lojalny pracownik",
    "oczekujemy lojalności",
    "lojalność wobec firmy",
    "długoterminowa współpraca",
    "szukamy kogoś na lata",
    "chcemy kogoś na stałe",
    "poszukujemy lojalnych pracowników",
    "stałe zaangażowanie",
    "lojalność to nasza wartość",
    "przywiązanie do firmy",
    "oczekujemy oddania",
    "nie zmieniaj pracy co rok",
    "szukamy pracownika na lata",
    "etat na zawsze",
    "my tu jesteśmy rodziną i tak ma zostać",
    "nie szukamy osób na chwilę",
    "zależy nam na długofalowej współpracy",
    "wymagamy lojalności",
    "nie zatrudniamy freelancerów",
    "poszukujemy kogoś kto zostanie z nami",
    "budowanie razem",
    "wspólna droga",
    "razem przez lata",
    "kariera w jednej firmie",

    # ========== 25. LIDER ZMIAN BEZ ZASOBÓW (odpowiedzialność bez narzędzi) ==========
    "lider zmian",
    "agent zmiany",
    "change agent",
    "change maker",
    "poszukiwany lider zmian",
    "inicjator zmian",
    "osoba która odmieni firmę",
    "katalizator zmian",
    "motorem zmian",
    "osoba napędzająca zmiany",
    "transformacja organizacyjna",
    "przeprowadzisz nas przez transformację",
    "zmienisz to co nie działa",
    "naprawisz procesy",
    "poprawisz to co złe",
    "wdrążysz nowe standardy",
    "odpowiadasz za zmiany",
    "masz wprowadzić nową jakość",
    "reorganizacja",
    "od nowa zbudujesz",
    "zmienisz kulturę organizacji",
    "zrewolucjonizujesz",
    "przekształcisz",
    "jesteś naszym zbawcą",
    "przyjdź i napraw",
    "naprawa firmy",
    "turnaround leader",
    "transformation leader",
    "change leadership",
    "reforma",
    "masz nas zmienić",

    # ========== 26. PRACA TO MISJA / POWOŁANIE (zapowiedź wykorzystywania) ==========
    "to więcej niż praca",
    "to nie jest zwykła praca",
    "szukamy misjonarzy",
    "praca jako misja",
    "nasza firma to misja",
    "zmieniamy świat",
    "jesteśmy na misji",
    "dołącz do misji",
    "praca z sensem",
    "praca która ma znaczenie",
    "praca która zmienia świat",
    "praca to służba",
    "służymy klientom",
    "mamy wyższy cel",
    "naszym celem jest coś więcej niż zysk",
    "jesteśmy tu dla czegoś więcej",
    "praca dla idei",
    "nie dla pieniędzy, dla idei",
    "misja ponad zysk",
    "cel nadrzędny",
    "działamy w słusznej sprawie",
    "ważna misja społeczna",
    "komercyjna misja",
    "cel > kasa",
    "wynagrodzenie drugorzędne",
    "liczy się misja a nie hajs",

    # ========== 27. NISKA KULTURA FEEDBACKU / KRYTYKI ==========
    "odporność na krytykę",
    "przyjmowanie krytyki",
    "konstruktywna krytyka (jako przykrywka hejtu)",
    "otwartość na feedback",
    "informacja zwrotna",
    "feedback na każdym kroku",
    "ciągły feedback",
    "feedback w czasie rzeczywistym",
    "nie każdy wytrzyma nasz feedback",
    "u nas feedback jest ostry",
    "feedback bez owijania w bawełnę",
    "mówimy wprost",
    "bez owijania",
    "prosto w oczy",
    "radzenie sobie z uwagami",
    "gruba skóra",
    "nie bierz do siebie",
    "nie obrażaj się",
    "nie przejmuj się krytyką",
    "krytyka to rozwój",
    "jak nie umiesz przyjmować krytyki, nie pasujesz",
    "feedback jest surowy",
    "feedback nie dla mięczaków",
    "twarda szkoła feedbacku",
    "nie oczekujemy dyplomacji",
    "mówimy, co myślimy",
    "szczerość kosztem kultury",

    # ========== 28. BRAK WORK-LIFE BALANCE ==========
    "praca to pasja",
    "praca to życie",
    "żyjemy pracą",
    "nie odcinamy się",
    "firma jest ważna",
    "praca jest ważniejsza niż życie prywatne",
    "weekendy nie są wolne",
    "urlop opcjonalny",
    "nie bierzemy urlopów",
    "my nie chorujemy",
    "L4 dla słabych",
    "nie bierzemy L4",
    "praca w chorobie",
    "nie ma czegoś takiego jak choroba",
    "obowiązek ponad zdrowie",
    "etat ponad wszystko",
    "praca 24/7",
    "ciągle w pracy",
    "brak życia prywatnego",
    "życie to praca",
    "praca pochłania",
    "praca w święta to norma",
    "praca w weekend to norma",
    "nie ma wolnych weekendów",
    "jesteśmy dostępni zawsze",
    "nie ma zwolnień lekarskich",
    "praca w każdych warunkach",

    # ========== 29. MY TU WSZYSCY JESTEŚMY ZAJĘCI / BRAK CZASU NA ROZWÓJ ==========
    "nie mamy czasu na rozwój",
    "brak czasu na wdrożenie",
    "ciężko o czas na dokumentację",
    "non stop zadania",
    "wszyscy są zajęci",
    "nie ma mentora, bo każdy ma swoje zadania",
    "nikt nie ma dla ciebie czasu",
    "rzucamy na głęboką wodę",
    "przecież dasz radę sam",
    "wszyscy są zajęci swoimi projektami",
    "brak opieki mentorskiej",
    "brak czasu na szkolenia",
    "nie mamy budżetu czasowego na rozwój",
    "rozwój we własnym zakresie",
    "onboarding trwa dzień",
    "wszystkiego nauczysz się w praktyce",
    "tu nie ma czasu na teorię",
    "od razu do roboty",
    "liczy się działanie a nie nauka",
    "nie ma czasu na czytanie dokumentacji",
    "dokumentacja nie istnieje",
    "wiedza jest w głowach, nie na wiki",
    "baza wiedzy nie istnieje",
    "nie mamy luka na SOP",

    # ========== 30. KONKURENCJA WEWNĘTRZNA / KANIBALIZM ZESPOŁOWY ==========
    "zdrowa rywalizacja",
    "rywalizacja między pracownikami",
    "rankingi pracowników",
    "tablica wyników",
    "walczymy o premie",
    "tylko najlepsi dostają",
    "system rywalizacji",
    "walka o klienta",
    "walka o prowizję",
    "rywalizacja zespołowa",
    "zawody o wyniki",
    "kto lepszy",
    "tylko zwycięzcy",
    "konkurs na wyniki",
    "pracownicy rywalizują",
    "teamy konkurują ze sobą",
    "jeden wygrywa, reszta przegrywa",
    "system rankingu",
    "performance ranking",
    "sales battle",
    "sales competition",
    "wewnętrzna rywalizacja",
    "bitwa o prowizję",
    "nie ma team spirit, jest walka",
    "zdrowa rywalizacja (nigdy nie jest zdrowa)",

    # ========== 31. WSZYSTKO JEST PRIORYTETEM ==========
    "wszystko priorytet",
    "każde zadanie pilne",
    "wszystkie terminy są ważne",
    "wiele priorytetów naraz",
    "priorytety się zmieniają",
    "dziś ważne, jutro nieważne",
    "ciągłe zmiany priorytetów",
    "nie wiadomo co najważniejsze",
    "lider zmienia zdanie co godzinę",
    "każde zadanie najważniejsze",
    "wszystko na wczoraj",
    "brak jasnych priorytetów",
    "ustalanie priorytetów to twój problem",
    "masz ogarnąć, co ważne",
    "wszystko jest ważne",
    "nie ma rzeczy mniej ważnych",
    "wszystkie projekty priorytetowe",
    "każdy klient priorytet",
    "każda sprawa pilna",
    "non stop zmiana priorytetów",

    # ========== 32. ZAUFANIE, ALE KONTROLA ==========
    "dajemy zaufanie, ale kontrolujemy",
    "zaufanie, ale weryfikacja",
    "pełne zaufanie, ale rozliczamy z każdego kroku",
    "jesteś wolny, ale musisz raportować",
    "autonomia, ale co godzina status",
    "możesz decydować, ale my zatwierdzamy",
    "samodzielność pod nadzorem",
    "jesteś odpowiedzialny, ale nie masz narzędzi",
    "zaufanie na dzień dobry, potem mikrozarządzanie",
    "jesteśmy jak rodzina, więc sprawdzamy każdy twój ruch",
    "sam planujesz, ale każdą zmianę konsultujesz",
    "elastyczność, ale tylko gdy pasuje do nas",
    "zespół się rozlicza",
    "daily standupy z rozliczeniem",
    "każda godzina rozliczona",
    "kontrola każdego zadania",
    "każda minuta pod lupą",
    "rejestracja czasu co do minuty",
    "kontrola aktywności",
    "monitoring pracy",
    "sprawdzamy co robisz",
    "wgląd w ekran",
    "audyt każdej czynności",
    "mikrozrządzenie",
    "micromanagement (nawet jak nie piszą wprost)",

    # ========== 33. NIE DLA LENIUCHÓW / „NIE DLA KAŻDEGO” ==========
    "nie dla każdego",
    "praca nie dla leniwych",
    "nie dla osób szukających łatwizny",
    "to nie jest praca dla każdego",
    "nie dla mięczaków",
    "praca dla twardzieli",
    "nie dla osób wrażliwych",
    "nie każdy to wytrzyma",
    "filtrujemy od razu",
    "jeśli nie jesteś gotowy na wyzwania, nie aplikuj",
    "nie dla ludzi którzy chcą mieć lekko",
    "praca nie dla osób po godzinie 16",
    "szukamy wojowników",
    "nie dla osób które chcą mieć łatwo",
    "to nie jest zwykła praca biurowa",
    "nie oczekujemy osób, które nie lubią wyzwań",
    "praca wymagająca charakteru",
    "nie dla każdego, tylko dla wybranych",
    "selekcja naturalna",
    "przetrwają najsilniejsi",
    "nie ma miejsca dla słabych",
    "nie ma litości",
    "hart ducha",
    "charakter trzeba mieć",
    "nie dla płaczków",
    "nie dla ludzi którzy się poddają",
    "nie dla osób które nie lubią presji",

    # ========== 34. OCZEKIWANIE NA GOTOWCA / SAMODZIELNEGO BEZ WSPARCIA ==========
    "samodzielny specjalista",
    "doświadczony i samodzielny",
    "nie potrzebuje wdrożenia",
    "szukamy gotowca",
    "kogoś od zaraz",
    "od ręki",
    "pracownik z własnym warsztatem",
    "nie oczekujemy wdrożenia",
    "zakładamy, że wszystko umiesz",
    "żadnego onboardingu",
    "mają być efekty od pierwszego dnia",
    "nie mamy czasu na naukę",
    "potrzebujemy kogoś na już",
    "wymagamy samodzielności",
    "zero wsparcia",
    "jesteś sam na placu boju",
    "nie ma buddy",
    "nie ma kogo pytać",
    "musisz sobie radzić sam",
    "oczekujemy pełnej autonomii od startu",
    "nie ma okresu wdrożeniowego",
    "ucz się na własnych błędach",
    "gotowiec na pozycję",
    "doświadczenie minimum 5 lat w każdej technologii",
    "mile widziane własne narzędzia",
    "przynosisz wiedzę i rozwiązania",
    "jesteś ekspertem, więc nie oczekuj pomocy",
]